# Generated by Django 5.1.1 on 2024-09-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetopic',
            name='data_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('LOCATION', 'Location')], default='OTHER', max_length=20),
        ),
    ]
