# Generated by Django 5.1.1 on 2024-09-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_node_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
