# Generated by Django 5.1.1 on 2024-09-21 20:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nodenote_disabled_alter_edge_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeembedding',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(dimensions=32),
        ),
    ]
