# Generated by Django 5.1.1 on 2024-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nodetopic_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetopic',
            name='data_type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('LOCATION', 'Location'), ('DATE', 'Date'), ('EVENT', 'Event'), ('PRODUCT', 'Product'), ('WORK_OF_ART', 'Work Of Art'), ('LAW', 'Law'), ('LANGUAGE', 'Language'), ('QUANTITY', 'Quantity'), ('PERCENT', 'Percent'), ('MONEY', 'Money'), ('TIME', 'Time'), ('URL', 'Url'), ('EMAIL', 'Email'), ('PHONE_NUMBER', 'Phone Number'), ('NATIONALITY', 'Nationality'), ('RELIGION', 'Religion'), ('TITLE', 'Title'), ('VEHICLE', 'Vehicle'), ('ANIMAL', 'Animal'), ('PLANT', 'Plant'), ('MEDICAL_CONDITION', 'Medical Condition'), ('SPORTS_TEAM', 'Sports Team'), ('INDUSTRY', 'Industry'), ('COMPANY', 'Company')], default='OTHER', max_length=20),
        ),
    ]
