# Generated by Django 5.1.1 on 2024-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_nodetopic_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodenote',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('LINK', 'Link')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nodenote',
            name='short_summary',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
