# Generated by Django 5.1.1 on 2024-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_nodetopic_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_node_embedding_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
