# Generated by Django 5.1.1 on 2024-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nodenote_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodenote',
            name='short_summary',
            field=models.TextField(null=True),
        ),
    ]
