# Generated by Django 5.1.1 on 2024-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_nodenote_short_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetopic',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
