services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /app/scripts/entrypoint-development.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - coredb
    environment:
      - DJANGO_SETTINGS_MODULE=contextlynx.settings
      - COREDB_NAME=${COREDB_NAME}
      - COREDB_USER=${COREDB_USER}
      - COREDB_PASSWORD=${COREDB_PASSWORD}
      - COREDB_HOST=coredb
      - DEBUG=False
      - ENVIRONMENT=production
    env_file:
      - .env

  coredb:
    image: pgvector/pgvector:pg16
    volumes:
      - contextlynx_coredb:/var/lib/postgresql/data/
      - ./scripts/init-development.sql:/docker-entrypoint-initdb.d/init-development.sql
    environment:
      - POSTGRES_DB=${COREDB_NAME}
      - POSTGRES_USER=${COREDB_USER}
      - POSTGRES_PASSWORD=${COREDB_PASSWORD}
    env_file:
      - .env

volumes:
  contextlynx_coredb: