name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - '**'  # This will trigger on all branches. Adjust as necessary.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Build Docker Image
        run: |
          tag="$(echo "${{ github.ref_name }}" | xargs | tr -c '[:alnum:]' '-')"
          cd app/contextlynx
          docker build -t ghcr.io/${{ github.repository }}/contextlynx:$tag-latest .

      - name: Push Docker Image
        run: |
          tag="$(echo "${{ github.ref_name }}" | xargs | tr -c '[:alnum:]' '-')"
          docker push ghcr.io/${{ github.repository }}/contextlynx:$tag-latest
